const citiesList= [
    {value:"עפולה" ,label:"עפולה"},
    {value:"עכו" ,label:"עכו"},
    {value:"ערד" ,label:"ערד"},
    {value:"אריאל" ,label:"אריאל"},
    {value:"אשדוד" ,label:"אשדוד"},
    {value:"אשקלון" ,label:"אשקלון"},
    {value:"בקעה על גרבייה" ,label:"בקעה על גרבייה"},
    {value:"בת ים" ,label:"בת ים"},
    {value:"באר שבע" ,label:"באר שבע"},
    {value:"בית שאן" ,label:"בית שאן"},
    {value:"בית שמש" ,label:"בית שמש"},
    {value:"ביתר עילית" ,label:"ביתר עילית"},
    {value:"בני ברק" ,label:"בני ברק"},
    {value:"דימונה" ,label:"דימונה"},
    {value:"אילת" ,label:"אילת"},
    {value:"אלעד" ,label:"אלעד"},
    {value:"גבעתיים" ,label:"גבעתיים"},
    {value:"חדרה" ,label:"חדרה"},
    {value:"חיפה" ,label:"חיפה"},
    {value:"חריש" ,label:"חריש"},
    {value:"הרצליה" ,label:"הרצליה"},
    {value:"הוד השרון" ,label:"הוד השרון"},
    {value:"חולון" ,label:"חולון"},
    {value:"ירושלים" ,label:"ירושלים"},
    {value:"כרמיאל" ,label:"כרמיאל"},
    {value:"כפר סבא" ,label:"כפר סבא"},
    {value:"קרית אתא" ,label:"קרית אתא"},
    {value:"קרית ביאליק" ,label:"קרית ביאליק"},
    {value:"קרית גת" ,label:"קרית גת"},
    {value:"קרית מלאכי" ,label:"קרית מלאכי"},
    {value:"קרית מוצקין" ,label:"קרית מוצקין"},
    {value:"קרית אונו" ,label:"קרית אונו"},
    {value:"קרית שמונה" ,label:"קרית שמונה"},
    {value:"קרית ים" ,label:"קרית ים"},
    {value:"לוד" ,label:"לוד"},
    {value:"מעלה אדומים" ,label:"מעלה אדומים"},
    {value:"מעלות-תרשיחא" ,label:"מעלות-תרשיחא"},
    {value:"מגדל העמק" ,label:"מגדל העמק"},
    {value:"מודיעין-מכבים-רעות" ,label:"מודיעין-מכבים-רעות"},
    {value:"נהריה" ,label:"נהריה"},
    {value:"נצרת" ,label:"נצרת"},
    {value:"נס ציונה" ,label:"נס ציונה"},
    {value:"נשר" ,label:"נשר"},
    {value:"נתניה" ,label:"נתניה"},
    {value:"נתיבות" ,label:"נתיבות"},
    {value:"נוף הגליל" ,label:"נוף הגליל"},
    {value:"אופקים" ,label:"אופקים"},
    {value:"אור עקיבא" ,label:"אור עקיבא"},
    {value:"אור יהודה" ,label:"אור יהודה"},
    {value:"פתח תקוה" ,label:"פתח תקוה"},
    {value:"קלנסווה" ,label:"קלנסווה"},
    {value:"רעננה" ,label:"רעננה"},
    {value:"רהט" ,label:"רהט"},
    {value:"רמת השרון" ,label:"רמת השרון"},
    {value:"רמת גן" ,label:"רמת גן"},
    {value:"רמלה" ,label:"רמלה"},
    {value:"רחובות" ,label:"רחובות"},
    {value:"ראשון לציון" ,label:"ראשון לציון"},
    {value:"ראש העין" ,label:"ראש העין"},
    {value:"סחנין" ,label:"סח'נין"},
    {value:"שדרות" ,label:"שדרות"},
    {value:"שפרעם" ,label:"שפרעם"},
    {value:"טייבה" ,label:"טייבה"},
    {value:"תמרה" ,label:"תמרה"},
    {value:"תל אביב-יפו" ,label:"תל אביב-יפו"},
    {value:"טבריה" ,label:"טבריה"},
    {value:"טירה" ,label:"טירה"},
    {value:"טירת כרמל" ,label:"טירת כרמל"},
    {value:"צפת" ,label:"צפת"},
    {value:"אום אל-פחם" ,label:"אום אל-פחם"},
    {value:"יבנה" ,label:"יבנה"},
    {value:"יהוד-מונוסון" ,label:"יהוד-מונוסון"},
    {value:"יקנעם" ,label:"יקנעם"}
];

export default citiesList;